---
title: "how_to_run_package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how_to_run_package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(SpatialIntegration)
library(stringr)
library(Seurat)
library(singlet)
library(ggplot2)
```


The commented out lines detail how the NMF embeddings were computed. This takes a large amount of compute, so for efficiency the objects have been saved after nmf embedding and can be loaded directly in.

# ```{r load geomx data and create suerat object}
# 
# #define file paths
# file_paths <- list(
#   "ACA_MOS_MOp_6mpi" = "/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/target_data_ACA_MOS_MOp_6mpi.RDS",
#   "ACA_MOS_MOp_9mpi" = "/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/target_data_ACA_MOS_MOp_9mpi.RDS",
#   "LAMDA" = "/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/target_data_LAMDA.RDS",
#   "MultiRegion" = "/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/target_data_MultiRegion.RDS",
#   "SNcAmygNew" = "/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/target_data_SNcAmygNew.RDS"
# )
# 
# 
# 
# #make suerat object
# seurat_object <- combine_datasets_into_seurat(file_paths)
# 
# 
# ```
# 
# 
# 
# ```{r get nmf embeddings}
# seurat_object <- process_and_run_nmf(seurat_object, nmf_rank = 5)
# RankPlot(seurat_object, detail.level = 2)
# 
# ```
# 
# 
# ```{r load reference Allen data}
# 
# Allen_SEA_AD_Atlas <- readRDS("/varidata/research/projects/henderson/THOMAS/Machine_Learning_For_Bioinformatics_Project/Reference_MTG_RNAseq_all-nuclei.2022-06-07.rds")
# 
# ```
# 
# 
# ```{r run NMF on allen data}
# Allen_SEA_AD_Atlas <- process_and_run_nmf(Allen_SEA_AD_Atlas, nmf_rank = 5)
# 
# ```
# 
# 
# ```{r save objects}
# saveRDS(seurat_object,"seurat_object.rds")
# saveRDS(Allen_SEA_AD_Atlas,"Allen_SEA_AD_Atlas.rds")
# ```


#how the subset object was made

# ```{r load in nmf embedded data}
# 
#  seurat_object <- readRDS("/varidata/research/projects/henderson/THOMAS/SpatialIntegration/SpatialIntegration/seurat_object.rds")
# Allen_SEA_AD_Atlas <- readRDS("/varidata/research/projects/henderson/THOMAS/SpatialIntegration/SpatialIntegration/Allen_SEA_AD_Atlas.rds")
# 
# # Replace NA values in the "subclass_label" column of @meta.data with "NA"
# Allen_SEA_AD_Atlas@meta.data[["subclass_label"]][is.na(Allen_SEA_AD_Atlas@meta.data[["subclass_label"]])] <- "NotLabled"
# 
# ```
# 
# 
# ```{r subset seurat object for upload to data file in package}
# 
# seurat_object_sub<-subset_seurat_by_proportions(seurat_object = seurat_object, cell_type_col="segment", 500)
# allen_sub<-subset_seurat_by_proportions(seurat_object = Allen_SEA_AD_Atlas, cell_type_col="subclass_label", 6000)
# 
# 
# ```
# 
# 
# 
# 
# 
# ```{r}
# 
#  seurat_merge<-merge_seurat_objects(seurat_object = seurat_object_sub, allen_sub)
# 
#  #save data to data file
#  use_data(seurat_merge, compress = "bzip2", overwrite = TRUE)
# 
# ```







```{r set lib path and install package}
#cahnge below libpath to directory with sufficient storage for large packages
.libPaths(c("/varidata/research/projects/henderson/THOMAS/R/4.4/library", .libPaths()))

install_github("Goralsth/spatialintegration")

library(SpatialIntegration)
```


```{r}

#load the data
data(seurat_merge)
is(seurat_merge, "Seurat")

seurat_merge
```








```{r}

seurat_merge<-process_and_run_nmf(seurat_merge, nmf_rank = 15)

```





```{r}


seurat_merge<-perform_gsea_and_clustering(seurat_merge)


```


```{r}
print(DimPlot(seurat_merge, reduction = "umap"))
print(DimPlot(seurat_merge, reduction = "umap", group.by ="segment"))
print(DimPlot(seurat_merge, reduction = "umap", group.by ="subclass_label"))
print(DimPlot(seurat_merge, reduction = "umap", group.by ="class_label"))
```


```{r}
plot_nmf_correlation_heatmap(seurat_merge, "cell_type_nmfFactor_corr.png")
```

```{r}

FeaturePlot(seurat_merge, features = paste0("NMF_", c(2,3,7,8,c(12:15))), raster = FALSE)

```





```{r}
plot_top20_enriched_pathways_single(seurat_object = seurat_merge,
  nmf_factor = 13,
  output_file = "top20_enriched_nmf6.pdf"
)


plot_top20_enriched_pathways_single(seurat_object = seurat_merge,
  nmf_factor = 15,
  output_file = "top20_enriched_nmf15.pdf"
)


```





```{r}

GSEAHeatmap(seurat_merge, reduction = "nmf", max.terms.per.factor = 50)
FeaturePlot(seurat_merge, features = paste0("NMF_", 1:10), raster = FALSE)
DimPlot(seurat_merge, reduction = "umap", group.by ="segment")
```













